services:
  - type: web
    name: chatbot-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: VITE_API_URL
        sync: false