services:
  - type: web
    name: chatbot-backend-production
    env: docker
    dockerfilePath: Dockerfile.prod
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: mysql://root:KFRKZaZrbwBIMedvYUftcUGQawxbPBwi@hopper.proxy.rlwy.net:51400/railway
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: FACEBOOK_PAGE_ACCESS_TOKEN
        sync: false
      - key: FACEBOOK_VERIFY_TOKEN
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false