import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from '../services/axiosInstance';
import flowService from '../services/flowService';

const Dashboard = () => {
  const [user, setUser] = useState(null);
  const [chatbots, setChatbots] = useState([]);
  const [loading, setLoading] = useState(true);
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [showIntegrationForm, setShowIntegrationForm] = useState(false);
  const [integrationType, setIntegrationType] = useState('facebook');
  const [integrationToken, setIntegrationToken] = useState('');
  const [showToken, setShowToken] = useState(false); // Added state for token visibility
  // Additional state for Facebook integration config
  const [pageId, setPageId] = useState('');
  const [appId, setAppId] = useState('');
  const [integrations, setIntegrations] = useState([]);
  // State for editing integration
  const [editingIntegrationId, setEditingIntegrationId] = useState(null);
  // State for flows
  const [chatbotFlows, setChatbotFlows] = useState({});
  // State for selected chatbot in integration form
  const [selectedChatbotId, setSelectedChatbotId] = useState('');
  const navigate = useNavigate();

  useEffect(() => {
    const token = localStorage.getItem('token');
    const userData = localStorage.getItem('user');
    
    if (!token || !userData) {
      navigate('/login');
      return;
    }
    
    setUser(JSON.parse(userData));
    fetchChatbots(token);
    fetchIntegrations(token);
  }, [navigate]);

  const fetchChatbots = async (token) => {
    try {
      const response = await axios.get('/chatbots', {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      
      // Ensure we're setting an array
      const chatbotsData = Array.isArray(response.data) ? response.data : [];
      setChatbots(chatbotsData);
      
      // Fetch flows for each chatbot
      chatbotsData.forEach(chatbot => {
        fetchFlowsForChatbot(chatbot.id, token);
      });
      
      setLoading(false);
    } catch (err) {
      console.error('Чатботуудыг татаж чадсангүй:', err);
      // Set to empty array on error
      setChatbots([]);
      setLoading(false);
    }
  };

  const fetchFlowsForChatbot = async (chatbotId, token) => {
    try {
      const flows = await flowService.getFlows(chatbotId, token);
      setChatbotFlows(prev => ({
        ...prev,
        [chatbotId]: flows
      }));
    } catch (err) {
      console.error(`Failed to fetch flows for chatbot ${chatbotId}:`, err);
      setChatbotFlows(prev => ({
        ...prev,
        [chatbotId]: []
      }));
    }
  };

  const fetchIntegrations = async (token) => {
    try {
      const response = await axios.get('/integrations', {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      
      // Ensure we're setting an array
      const integrationsData = Array.isArray(response.data) ? response.data : [];
      setIntegrations(integrationsData);
    } catch (err) {
      console.error('Интеграциудыг татаж чадсангүй:', err);
      // Set to empty array on error
      setIntegrations([]);
    }
  };

  const handleCreateChatbot = async (e) => {
    e.preventDefault();
    const token = localStorage.getItem('token');
    
    try {
      const response = await axios.post('/chatbots', {
        name,
        description
      }, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      
      setChatbots([...chatbots, response.data]);
      setName('');
      setDescription('');
    } catch (err) {
      console.error('Чатбот үүсгэж чадсангүй:', err);
    }
  };

  const handleAddIntegration = async (e) => {
    e.preventDefault();
    const token = localStorage.getItem('token');
    
    try {
      // Prepare integration data based on type
      const integrationData = {
        type: integrationType,
        token: integrationToken
      };
      
      // Add chatbotId if selected
      if (selectedChatbotId) {
        integrationData.chatbotId = selectedChatbotId;
      }
      
      // Add config for Facebook/Instagram integration
      if (integrationType === 'facebook' || integrationType === 'instagram') {
        integrationData.config = {
          pageId: pageId,
          // verifyToken will be generated by the backend
          appId: appId
        };
      }
      
      const response = await axios.post('/integrations', 
        integrationData,
        {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        }
      );
      
      // If it's a Facebook/Instagram integration, generate verify token
      if ((integrationType === 'facebook' || integrationType === 'instagram') && response.data.id) {
        try {
          const verifyResponse = await axios.post(
            `/integrations/${response.data.id}/generate-verify-token`,
            {},
            {
              headers: {
                'Authorization': `Bearer ${token}`
              }
            }
          );
          
          console.log('Verify token generated:', verifyResponse.data.verifyToken);
          alert(`Verify token generated: ${verifyResponse.data.verifyToken}`);
          
          // Update the integration in state with the new verify token
          setIntegrations([...integrations, {
            ...response.data,
            config: {
              ...response.data.config,
              verifyToken: verifyResponse.data.verifyToken
            }
          }]);
        } catch (verifyError) {
          console.error('Failed to generate verify token:', verifyError);
          // Still add the integration without the verify token
          setIntegrations([...integrations, response.data]);
        }
      } else {
        setIntegrations([...integrations, response.data]);
      }
      
      setIntegrationToken('');
      // Reset Facebook/Instagram config fields
      setPageId('');
      setAppId('');
      setSelectedChatbotId('');
      setShowIntegrationForm(false);
    } catch (err) {
      console.error('Интеграци нэмж чадсангүй:', err);
      alert('Интеграци нэмж чадсангүй: ' + (err.response?.data?.error || err.message));
    }
  };

  const handleLogout = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    navigate('/login');
  };

  const handleDeleteChatbot = async (chatbotId) => {
    const token = localStorage.getItem('token');
    
    try {
      await axios.delete(`/chatbots/${chatbotId}`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      
      // Remove the deleted chatbot from the state
      setChatbots(chatbots.filter(chatbot => chatbot.id !== chatbotId));
      // Also remove its flows from state
      setChatbotFlows(prev => {
        const newFlows = { ...prev };
        delete newFlows[chatbotId];
        return newFlows;
      });
    } catch (err) {
      console.error('Чатботыг устгаж чадсангүй:', err);
    }
  };

  const handleDeleteIntegration = async (integrationId) => {
    const token = localStorage.getItem('token');
    
    try {
      await axios.delete(`/integrations/${integrationId}`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      
      // Remove the deleted integration from the state
      setIntegrations(integrations.filter(integration => integration.id !== integrationId));
    } catch (err) {
      console.error('Интеграци устгаж чадсангүй:', err);
    }
  };

  const handleEditIntegration = (integration) => {
    setEditingIntegrationId(integration.id);
    setIntegrationType(integration.type);
    setIntegrationToken(integration.token || '');
    setSelectedChatbotId(integration.chatbotId || '');
    
    // Populate Facebook/Instagram config fields if it's a Facebook/Instagram integration
    if ((integration.type === 'facebook' || integration.type === 'instagram') && integration.config) {
      setPageId(integration.config.pageId || '');
      setAppId(integration.config.appId || '');
    }
    
    setShowIntegrationForm(true);
  };

  const handleUpdateIntegration = async (e) => {
    e.preventDefault();
    const token = localStorage.getItem('token');
    
    try {
      // Prepare integration data based on type
      const integrationData = {
        type: integrationType,
        token: integrationToken
      };
      
      // Add chatbotId if selected
      if (selectedChatbotId) {
        integrationData.chatbotId = selectedChatbotId;
      }
      
      // Add config for Facebook/Instagram integration
      if (integrationType === 'facebook' || integrationType === 'instagram') {
        integrationData.config = {
          pageId: pageId,
          appId: appId
        };
      }
      
      const response = await axios.put(`/integrations/${editingIntegrationId}`, 
        integrationData,
        {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        }
      );
      
      // Update the integration in the state
      setIntegrations(integrations.map(integration => 
        integration.id === editingIntegrationId ? response.data : integration
      ));
      
      setEditingIntegrationId(null);
      setIntegrationToken('');
      // Reset Facebook/Instagram config fields
      setPageId('');
      setAppId('');
      setSelectedChatbotId('');
      setShowIntegrationForm(false);
    } catch (err) {
      console.error('Интеграци шинэчилж чадсангүй:', err);
      alert('Интеграци шинэчилж чадсангүй: ' + (err.response?.data?.error || err.message));
    }
  };

  const handleGenerateVerifyToken = async (integrationId) => {
    const token = localStorage.getItem('token');
    
    try {
      const response = await axios.post(
        `/integrations/${integrationId}/generate-verify-token`,
        {},
        {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        }
      );
      
      console.log('Verify token generated:', response.data.verifyToken);
      alert(`Verify token generated: ${response.data.verifyToken}`);
      
      // Update the integration in the state with the new verify token
      setIntegrations(integrations.map(integration => {
        if (integration.id === integrationId) {
          return {
            ...integration,
            config: {
              ...integration.config,
              verifyToken: response.data.verifyToken
            }
          };
        }
        return integration;
      }));
    } catch (err) {
      console.error('Failed to generate verify token:', err);
      alert('Failed to generate verify token: ' + (err.response?.data?.error || err.message));
    }
  };

  const handleTestToken = async (integrationId) => {
    const token = localStorage.getItem('token');
    
    try {
      const response = await axios.post(
        `/integrations/${integrationId}/generate-verify-token`,
        {},
        {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        }
      );
      
      console.log('Verify token generated:', response.data.verifyToken);
      alert(`Verify token generated: ${response.data.verifyToken}`);
      
      // Update the integration in the state with the new verify token
      setIntegrations(integrations.map(integration => {
        if (integration.id === integrationId) {
          return {
            ...integration,
            config: {
              ...integration.config,
              verifyToken: response.data.verifyToken
            }
          };
        }
        return integration;
      }));
    } catch (err) {
      console.error('Failed to generate verify token:', err);
      alert('Failed to generate verify token: ' + (err.response?.data?.error || err.message));
    }
  };

  if (loading) {
    return <div className="dashboard">Ачааллаж байна...</div>;
  }

  return (
    <div className="dashboard">
      <header className="card">
        <h1>Хяналтын самбар</h1>
        <div className="user-info">
          <span>Тавтай морилно уу, {user?.name || user?.email}</span>
          <button onClick={handleLogout} className="btn secondary">Гарах</button>
        </div>
      </header>
      
      <main>
        <section className="create-chatbot card">
          <h2>Шинэ чатбот үүсгэх</h2>
          <form onSubmit={handleCreateChatbot}>
            <div className="form-group">
              <label htmlFor="name">Чатботын нэр</label>
              <input
                type="text"
                id="name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
                placeholder="Жишээ: Үйлчилгээний бот"
              />
            </div>
            
            <div className="form-group">
              <label htmlFor="description">Тайлбар</label>
              <textarea
                id="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows="3"
                placeholder="Чатботынхаа үүрэг үйлчилгээг тайлбарлана уу..."
              />
            </div>
            
            <button type="submit" className="btn primary">Чатбот үүсгэх</button>
          </form>
        </section>
        
        <section className="integrations card">
          <div className="integrations-header">
            <h2>Нийтийн сүлжээний интеграци</h2>
            <button 
              onClick={() => {
                setShowIntegrationForm(!showIntegrationForm);
                setEditingIntegrationId(null);
                // Reset form fields when opening for new integration
                if (!showIntegrationForm) {
                  setIntegrationToken('');
                  setPageId('');
                  setAppId('');
                  setSelectedChatbotId('');
                  setShowToken(false); // Reset token visibility
                }
              }}
              className="btn secondary"
            >
              {showIntegrationForm ? 'Цуцлах' : 'Интеграци нэмэх'}
            </button>
          </div>
          
          {showIntegrationForm && (
            <form onSubmit={editingIntegrationId ? handleUpdateIntegration : handleAddIntegration} className="integration-form card">
              <h3>{editingIntegrationId ? 'Интеграци шинэчлэх' : 'Интеграци нэмэх'}</h3>
              <div className="form-group">
                <label htmlFor="integrationType">Платформ</label>
                <select
                  id="integrationType"
                  value={integrationType}
                  onChange={(e) => setIntegrationType(e.target.value)}
                  disabled={editingIntegrationId} // Can't change type when editing
                >
                  <option value="facebook">Facebook</option>
                  <option value="instagram">Instagram</option>
                </select>
              </div>
              
              <div className="form-group">
                <label htmlFor="integrationToken">Хандалтын токен</label>
                <div className="relative">
                  <input
                    type={showToken ? "text" : "password"}
                    id="integrationToken"
                    value={integrationToken}
                    onChange={(e) => setIntegrationToken(e.target.value)}
                    required
                    placeholder="Хандалтын токеноо оруулна уу"
                    className="w-full pr-10"
                  />
                  <button
                    type="button"
                    onClick={() => setShowToken(!showToken)}
                    className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-500 hover:text-gray-700"
                  >
                    {showToken ? (
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M10 12a2 2 0 100-4 2 2 0 000 4z" />
                        <path fillRule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clipRule="evenodd" />
                      </svg>
                    ) : (
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M3.707 2.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-1.473-1.473A10.014 10.014 0 0019.542 10C18.268 5.943 14.478 3 10 3a9.958 9.958 0 00-4.512 1.074l-1.78-1.781zm4.261 4.26l1.514 1.515a2.003 2.003 0 012.45 2.45l1.514 1.514a4 4 0 00-5.478-5.478z" clipRule="evenodd" />
                        <path d="M12.454 16.697L9.75 13.992a4 4 0 01-3.742-3.741L2.335 6.578A9.98 9.98 0 00.458 10c1.274 4.057 5.065 7 9.542 7 .847 0 1.669-.105 2.454-.303z" />
                      </svg>
                    )}
                  </button>
                </div>
              </div>
              
              {/* Additional fields for Facebook/Instagram integration */}
              {(integrationType === 'facebook' || integrationType === 'instagram') && (
                <>
                  <div className="form-group">
                    <label htmlFor="pageId">{integrationType === 'instagram' ? 'Instagram Account ID' : 'Page ID'}</label>
                    <input
                      type="text"
                      id="pageId"
                      value={pageId}
                      onChange={(e) => setPageId(e.target.value)}
                      required
                      placeholder={integrationType === 'instagram' ? 'Instagram Account ID' : 'Facebook Page ID'}
                    />
                  </div>
                  
                  <div className="form-group">
                    <label htmlFor="appId">App ID</label>
                    <div className="relative">
                      <input
                        type={showToken ? "text" : "password"}
                        id="appId"
                        value={appId}
                        onChange={(e) => setAppId(e.target.value)}
                        required
                        placeholder="Facebook App ID"
                        className="w-full pr-10"
                      />
                      <button
                        type="button"
                        onClick={() => setShowToken(!showToken)}
                        className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-500 hover:text-gray-700"
                      >
                        {showToken ? (
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                            <path d="M10 12a2 2 0 100-4 2 2 0 000 4z" />
                            <path fillRule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clipRule="evenodd" />
                          </svg>
                        ) : (
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                            <path fillRule="evenodd" d="M3.707 2.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-1.473-1.473A10.014 10.014 0 0019.542 10C18.268 5.943 14.478 3 10 3a9.958 9.958 0 00-4.512 1.074l-1.78-1.781zm4.261 4.26l1.514 1.515a2.003 2.003 0 012.45 2.45l1.514 1.514a4 4 0 00-5.478-5.478z" clipRule="evenodd" />
                            <path d="M12.454 16.697L9.75 13.992a4 4 0 01-3.742-3.741L2.335 6.578A9.98 9.98 0 00.458 10c1.274 4.057 5.065 7 9.542 7 .847 0 1.669-.105 2.454-.303z" />
                          </svg>
                        )}
                      </button>
                    </div>
                  </div>
                  
                  <div className="form-group">
                    <label htmlFor="selectedChatbot">Холбох чатбот</label>
                    <select
                      id="selectedChatbot"
                      value={selectedChatbotId}
                      onChange={(e) => setSelectedChatbotId(e.target.value)}
                      className="w-full p-2 border border-gray-300 rounded-lg"
                    >
                      <option value="">Чатбот сонгох</option>
                      {chatbots.map((chatbot) => (
                        <option key={chatbot.id} value={chatbot.id}>
                          {chatbot.name}
                        </option>
                      ))}
                    </select>
                    <p className="text-sm text-gray-500 mt-1">
                      Энэ нийтийн сүлжээний интеграцийг аль чатботод холбохыг сонгоно уу
                    </p>
                  </div>
                </>
              )}
              
              <div className="form-actions">
                <button type="submit" className="btn primary">
                  {editingIntegrationId ? 'Шинэчлэх' : 'Интеграци нэмэх'}
                </button>
                <button 
                  type="button" 
                  onClick={() => {
                    setShowIntegrationForm(false);
                    setEditingIntegrationId(null);
                    // Reset form fields
                    setIntegrationToken('');
                    setPageId('');
                    setAppId('');
                    setSelectedChatbotId('');
                    setShowToken(false); // Reset token visibility
                  }}
                  className="btn secondary"
                >
                  Цуцлах
                </button>
              </div>
            </form>
          )}
          
          {Array.isArray(integrations) && integrations.length > 0 ? (
            <div className="integrations-list">
              {integrations.map((integration) => (
                <div key={integration?.id} className="integration-item">
                  <div className="integration-info">
                    <span className="integration-type">{integration.type}</span>
                    {integration.chatbotId && integration.chatbot && (
                      <span className="integration-chatbot">
                        Чатбот: {integration.chatbot.name}
                      </span>
                    )}
                    {integration.config && typeof integration.config === 'object' && (
                      <>
                        <span className="integration-config">
                          {(integration.type === 'facebook' || integration.type === 'instagram') && integration.config.pageId && 
                            (integration.type === 'instagram' ? `Instagram ID: ${integration.config.pageId}` : `Page: ${integration.config.pageId}`)}
                        </span>
                        {(integration.type === 'facebook' || integration.type === 'instagram') && integration.config.verifyToken && (
                          <div className="form-group mt-2">
                            <label className="text-sm text-gray-600">Verify Token:</label>
                            <div className="flex">
                              <input
                                type="text"
                                value={integration.config.verifyToken}
                                disabled
                                className="flex-1 p-1 text-sm border border-gray-300 rounded bg-gray-100"
                              />
                              <button
                                onClick={() => handleGenerateVerifyToken(integration.id)}
                                className="ml-2 px-2 py-1 bg-blue-500 text-white text-sm rounded hover:bg-blue-600"
                              >
                                Шинэчлэх
                              </button>
                            </div>
                          </div>
                        )}
                      </>
                    )}
                    <span className="integration-date">
                      Нэмсэн: {new Date(integration.createdAt).toLocaleDateString()}
                    </span>
                  </div>
                  <div className="integration-actions">
                    {(integration.type === 'facebook' || integration.type === 'instagram') && (
                      <button 
                        onClick={() => handleTestToken(integration.id)}
                        className="btn secondary small mr-2"
                      >
                        Токен шалгах
                      </button>
                    )}
                    <button 
                      onClick={() => handleEditIntegration(integration)}
                      className="btn secondary small mr-2"
                    >
                      Засах
                    </button>
                    <button 
                      onClick={() => handleDeleteIntegration(integration.id)}
                      className="btn danger small"
                    >
                      Устгах
                    </button>
                  </div>

                </div>
              ))}
            </div>
          ) : (
            <p>Одоохондоо нийтийн сүлжээний интеграци нэмээгүй байна. Чатботоо Facebook эсвэл Instagram-тай холбоно уу.</p>
          )}
        </section>
        
        <section className="chatbots-list card">
          <h2>Таны чатботууд</h2>
          {Array.isArray(chatbots) && chatbots.length === 0 ? (
            <p>Та одоохондоо чатбот үүсгээгүй байна. Эхний чатботоо үүсгээд эхлээрэй!</p>
          ) : (
            <div className="chatbots-grid">
              {Array.isArray(chatbots) && chatbots.map((chatbot) => (
                <div key={chatbot?.id} className="chatbot-card card">
                  <h3>{chatbot?.name}</h3>
                  <p>{chatbot?.description || 'Тайлбар оруулаагүй'}</p>
                  <div className="chatbot-stats">
                    <span>Харилцан яриа: {chatbot?.conversations?.length || 0}</span>
                  </div>
                  <div className="chatbot-flows">
                    <div className="flex justify-between items-center">
                      <h4>Урсгалууд:</h4>
                      <button 
                        onClick={() => navigate(`/flow-builder/${chatbot.id}/new`)}
                        className="btn secondary small"
                      >
                        Шинэ урсгал
                      </button>
                    </div>
                    {chatbotFlows[chatbot.id] && chatbotFlows[chatbot.id].length > 0 ? (
                      <ul>
                        {chatbotFlows[chatbot.id].map(flow => (
                          <li key={flow.id} className="flow-item">
                            <span>{flow.name}</span>
                            <button 
                              onClick={() => navigate(`/flow-builder/${chatbot.id}/${flow.id}`)}
                              className="btn secondary small"
                            >
                              Засах
                            </button>
                          </li>
                        ))}
                      </ul>
                    ) : (
                      <div className="flex flex-col items-center justify-center p-4 text-center">
                        <p className="mb-4">Энэ чатботод одоогоор урсгал оруулаагүй байна.</p>
                        <button 
                          onClick={() => navigate(`/flow-builder/${chatbot.id}/new`)}
                          className="btn primary"
                        >
                          Эхний урсгалаа үүсгэх
                        </button>
                      </div>
                    )}
                  </div>
                  <div className="chatbot-actions">
                    <button 
                      onClick={() => navigate(`/chat/${chatbot?.id}`)}
                      className="btn secondary"
                    >
                      Чатлах
                    </button>
                    <button 
                      onClick={() => handleDeleteChatbot(chatbot?.id)}
                      className="btn secondary"
                    >
                      Устгах
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>
      </main>
    </div>
  );
};

export default Dashboard;